### ISSUE TITLE
Remove os.environ['MAVLINK20'] = '1' from all tools

### ISSUE THREAD

**Issue by clydemcqueen** [clydemcqueen/ardusub_log_tools#5]
Summary: the line `os.environ['MAVLINK20'] = '1'` isn't doing anything, and it should be removed.

Longer story:

To set the MAVLink wire protocol to 2.0 you need to set `os.environ['MAVLINK20'] = '1'` _before_ importing pymavlink. Setting the wire protocol only matters when writing (packing) new messages; when reading (unpacking) the wire protocol is determined by the magic byte (0xFE vs 0xFD) in the message. None of the tools write new messages, so we don't need this line, and probably don't need the `import os` as well. 

[MAVLink version reference](https://mavlink.io/en/guide/mavlink_version.html)

**Comment by billmania** [comment]
I've never held MAVLink in very high regard. Issues (or "features") like this maintain that ill repute. :wink:
